# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/mkrtichkuloian/Desktop/Mkrtich Kuloian/hobbies/programming/projects/ctuix"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/mkrtichkuloian/Desktop/Mkrtich Kuloian/hobbies/programming/projects/ctuix"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/mkrtichkuloian/Desktop/Mkrtich Kuloian/hobbies/programming/projects/ctuix/CMakeFiles" "/Users/mkrtichkuloian/Desktop/Mkrtich Kuloian/hobbies/programming/projects/ctuix//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/mkrtichkuloian/Desktop/Mkrtich Kuloian/hobbies/programming/projects/ctuix/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ctuix

# Build rule for target.
ctuix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ctuix
.PHONY : ctuix

# fast build rule for target.
ctuix/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/build
.PHONY : ctuix/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named ctuix_demo

# Build rule for target.
ctuix_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ctuix_demo
.PHONY : ctuix_demo

# fast build rule for target.
ctuix_demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix_demo.dir/build.make CMakeFiles/ctuix_demo.dir/build
.PHONY : ctuix_demo/fast

#=============================================================================
# Target rules for targets named demo

# Build rule for target.
demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo
.PHONY : demo

# fast build rule for target.
demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/build
.PHONY : demo/fast

demo/ctuix_demo.o: demo/ctuix_demo.c.o
.PHONY : demo/ctuix_demo.o

# target to build an object file
demo/ctuix_demo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix_demo.dir/build.make CMakeFiles/ctuix_demo.dir/demo/ctuix_demo.c.o
.PHONY : demo/ctuix_demo.c.o

demo/ctuix_demo.i: demo/ctuix_demo.c.i
.PHONY : demo/ctuix_demo.i

# target to preprocess a source file
demo/ctuix_demo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix_demo.dir/build.make CMakeFiles/ctuix_demo.dir/demo/ctuix_demo.c.i
.PHONY : demo/ctuix_demo.c.i

demo/ctuix_demo.s: demo/ctuix_demo.c.s
.PHONY : demo/ctuix_demo.s

# target to generate assembly for a file
demo/ctuix_demo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix_demo.dir/build.make CMakeFiles/ctuix_demo.dir/demo/ctuix_demo.c.s
.PHONY : demo/ctuix_demo.c.s

src/ctuix_core.o: src/ctuix_core.c.o
.PHONY : src/ctuix_core.o

# target to build an object file
src/ctuix_core.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_core.c.o
.PHONY : src/ctuix_core.c.o

src/ctuix_core.i: src/ctuix_core.c.i
.PHONY : src/ctuix_core.i

# target to preprocess a source file
src/ctuix_core.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_core.c.i
.PHONY : src/ctuix_core.c.i

src/ctuix_core.s: src/ctuix_core.c.s
.PHONY : src/ctuix_core.s

# target to generate assembly for a file
src/ctuix_core.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_core.c.s
.PHONY : src/ctuix_core.c.s

src/ctuix_draw.o: src/ctuix_draw.c.o
.PHONY : src/ctuix_draw.o

# target to build an object file
src/ctuix_draw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_draw.c.o
.PHONY : src/ctuix_draw.c.o

src/ctuix_draw.i: src/ctuix_draw.c.i
.PHONY : src/ctuix_draw.i

# target to preprocess a source file
src/ctuix_draw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_draw.c.i
.PHONY : src/ctuix_draw.c.i

src/ctuix_draw.s: src/ctuix_draw.c.s
.PHONY : src/ctuix_draw.s

# target to generate assembly for a file
src/ctuix_draw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_draw.c.s
.PHONY : src/ctuix_draw.c.s

src/ctuix_error.o: src/ctuix_error.c.o
.PHONY : src/ctuix_error.o

# target to build an object file
src/ctuix_error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_error.c.o
.PHONY : src/ctuix_error.c.o

src/ctuix_error.i: src/ctuix_error.c.i
.PHONY : src/ctuix_error.i

# target to preprocess a source file
src/ctuix_error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_error.c.i
.PHONY : src/ctuix_error.c.i

src/ctuix_error.s: src/ctuix_error.c.s
.PHONY : src/ctuix_error.s

# target to generate assembly for a file
src/ctuix_error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_error.c.s
.PHONY : src/ctuix_error.c.s

src/ctuix_key.o: src/ctuix_key.c.o
.PHONY : src/ctuix_key.o

# target to build an object file
src/ctuix_key.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_key.c.o
.PHONY : src/ctuix_key.c.o

src/ctuix_key.i: src/ctuix_key.c.i
.PHONY : src/ctuix_key.i

# target to preprocess a source file
src/ctuix_key.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_key.c.i
.PHONY : src/ctuix_key.c.i

src/ctuix_key.s: src/ctuix_key.c.s
.PHONY : src/ctuix_key.s

# target to generate assembly for a file
src/ctuix_key.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_key.c.s
.PHONY : src/ctuix_key.c.s

src/ctuix_nav.o: src/ctuix_nav.c.o
.PHONY : src/ctuix_nav.o

# target to build an object file
src/ctuix_nav.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_nav.c.o
.PHONY : src/ctuix_nav.c.o

src/ctuix_nav.i: src/ctuix_nav.c.i
.PHONY : src/ctuix_nav.i

# target to preprocess a source file
src/ctuix_nav.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_nav.c.i
.PHONY : src/ctuix_nav.c.i

src/ctuix_nav.s: src/ctuix_nav.c.s
.PHONY : src/ctuix_nav.s

# target to generate assembly for a file
src/ctuix_nav.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_nav.c.s
.PHONY : src/ctuix_nav.c.s

src/ctuix_parse.o: src/ctuix_parse.c.o
.PHONY : src/ctuix_parse.o

# target to build an object file
src/ctuix_parse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_parse.c.o
.PHONY : src/ctuix_parse.c.o

src/ctuix_parse.i: src/ctuix_parse.c.i
.PHONY : src/ctuix_parse.i

# target to preprocess a source file
src/ctuix_parse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_parse.c.i
.PHONY : src/ctuix_parse.c.i

src/ctuix_parse.s: src/ctuix_parse.c.s
.PHONY : src/ctuix_parse.s

# target to generate assembly for a file
src/ctuix_parse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_parse.c.s
.PHONY : src/ctuix_parse.c.s

src/ctuix_tree.o: src/ctuix_tree.c.o
.PHONY : src/ctuix_tree.o

# target to build an object file
src/ctuix_tree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_tree.c.o
.PHONY : src/ctuix_tree.c.o

src/ctuix_tree.i: src/ctuix_tree.c.i
.PHONY : src/ctuix_tree.i

# target to preprocess a source file
src/ctuix_tree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_tree.c.i
.PHONY : src/ctuix_tree.c.i

src/ctuix_tree.s: src/ctuix_tree.c.s
.PHONY : src/ctuix_tree.s

# target to generate assembly for a file
src/ctuix_tree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_tree.c.s
.PHONY : src/ctuix_tree.c.s

src/ctuix_utils.o: src/ctuix_utils.c.o
.PHONY : src/ctuix_utils.o

# target to build an object file
src/ctuix_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_utils.c.o
.PHONY : src/ctuix_utils.c.o

src/ctuix_utils.i: src/ctuix_utils.c.i
.PHONY : src/ctuix_utils.i

# target to preprocess a source file
src/ctuix_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_utils.c.i
.PHONY : src/ctuix_utils.c.i

src/ctuix_utils.s: src/ctuix_utils.c.s
.PHONY : src/ctuix_utils.s

# target to generate assembly for a file
src/ctuix_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctuix.dir/build.make CMakeFiles/ctuix.dir/src/ctuix_utils.c.s
.PHONY : src/ctuix_utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... clean-all"
	@echo "... demo"
	@echo "... ctuix"
	@echo "... ctuix_demo"
	@echo "... demo/ctuix_demo.o"
	@echo "... demo/ctuix_demo.i"
	@echo "... demo/ctuix_demo.s"
	@echo "... src/ctuix_core.o"
	@echo "... src/ctuix_core.i"
	@echo "... src/ctuix_core.s"
	@echo "... src/ctuix_draw.o"
	@echo "... src/ctuix_draw.i"
	@echo "... src/ctuix_draw.s"
	@echo "... src/ctuix_error.o"
	@echo "... src/ctuix_error.i"
	@echo "... src/ctuix_error.s"
	@echo "... src/ctuix_key.o"
	@echo "... src/ctuix_key.i"
	@echo "... src/ctuix_key.s"
	@echo "... src/ctuix_nav.o"
	@echo "... src/ctuix_nav.i"
	@echo "... src/ctuix_nav.s"
	@echo "... src/ctuix_parse.o"
	@echo "... src/ctuix_parse.i"
	@echo "... src/ctuix_parse.s"
	@echo "... src/ctuix_tree.o"
	@echo "... src/ctuix_tree.i"
	@echo "... src/ctuix_tree.s"
	@echo "... src/ctuix_utils.o"
	@echo "... src/ctuix_utils.i"
	@echo "... src/ctuix_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

