<!ELEMENT ctuix (ctuix_panel | ctuix_selection_box | ctuix_scroll_panel)+>

<!ELEMENT ctuix_panel (ctuix_label | ctuix_button | ctuix_entry | ctuix_panel | ctuix_selection_box | ctuix_scroll_panel)*>
<!ELEMENT ctuix_selection_box (ctuix_label | ctuix_button | ctuix_entry | ctuix_panel | ctuix_selection_box | ctuix_scroll_panel)*>
<!ELEMENT ctuix_scroll_panel (ctuix_label | ctuix_button | ctuix_entry | ctuix_panel | ctuix_selection_box | ctuix_scroll_panel)*>

<!ELEMENT ctuix_label (#PCDATA)>
<!ELEMENT ctuix_button (#PCDATA)>
<!ELEMENT ctuix_entry EMPTY>

<!ATTLIST ctuix_panel layout (grid | horizontal | vertical) "vertical" x CDATA #REQUIRED y CDATA #REQUIRED w CDATA #REQUIRED h CDATA #REQUIRED user_input (true | false) "false" name CDATA #IMPLIED>
<!ATTLIST ctuix_selection_box layout (horizontal | vertical) "vertical" x CDATA #REQUIRED y CDATA #REQUIRED w CDATA #REQUIRED h CDATA #REQUIRED user_input (true | false) "false" name CDATA #IMPLIED>
<!ATTLIST ctuix_scroll_panel layout (horizontal | vertical) "vertical" x CDATA #REQUIRED y CDATA #REQUIRED w CDATA #REQUIRED h CDATA #REQUIRED user_input (true | false) "false" name CDATA #IMPLIED>

<!ATTLIST ctuix_label x CDATA #REQUIRED y CDATA #REQUIRED w CDATA #REQUIRED h CDATA #REQUIRED user_input (true | false) "false" name CDATA #IMPLIED>
<!ATTLIST ctuix_button x CDATA #REQUIRED y CDATA #REQUIRED w CDATA #REQUIRED h CDATA #REQUIRED user_input (true | false) "false" name CDATA #IMPLIED>
<!ATTLIST ctuix_entry x CDATA #REQUIRED y CDATA #REQUIRED w CDATA #REQUIRED h CDATA #REQUIRED user_input (true | false) "false" name CDATA #IMPLIED>